#!/bin/sh
# swu_satte_machine - A shell script to check system state after update
SCRIPTS_PATH="/opt/scripts"
source "${SCRIPTS_PATH}/env_var"

chech_update_state_value () {

  case $UPDATE_STATE in 
    "WAIT") source "$SCRIPTS_PATH/boot.sh" ;;
    "GET_APP_ARCHIVE_NAME" | "GET_APP_ARCHIVE" | "GET_ROOTFS_NAME" | "UPDATE_SYSTEM" |"UPDATE_APP") "$SCRIPTS_PATH/get_archive_name.sh" ;;
    "SYSTEM_UPDATED") mount $TEMP_APP_PART /APP ; "$SCRIPTS_PATH/rootfs_verification.sh" ;;
    "APP_UPDATED") mount $TEMP_APP_PART /APP ; "$SCRIPTS_PATH/app_verification.sh";;
    esac 
}

  check_update_state

source "${SCRIPTS_PATH}/save_env"
