#!/bin/sh
# swu_satte_machine - A shell script to check system state after update

# Variable
SCRIPTS_PATH="/opt/scripts"
ENVIRONNEMENT_SCRIPT_PATH="$SCRIPTS_PATH/env_var"

# Source environnement variables
source $ENVIRONNEMENT_SCRIPT_PATH

check_update_state_value () {

  case $UPDATE_STATE in 
    "WAIT") source $WAIT_UPDATE_SCRIPT ;; # All is ok
    "GET_APP_ARCHIVE_NAME" | "GET_APP_ARCHIVE" | "GET_ROOTFS_NAME" | "UPDATE_SYSTEM" |"UPDATE_APP") source $GET_ARCHIVE_SCRIPT ;; # The update was interrupted 
    "SYSTEM_UPDATED") mount $TEMP_APP_PART /APP; source $ROOTFS_VERIFICATION_SCRIPT ;; # Rootfs and Application partitions were updated
    "APP_UPDATED") mount $TEMP_APP_PART /APP ; source $APP_VERIFICATION_SCRIPT ;; # Only Application partition was updated
    esac 
}

check_update_state_value
# Save environnement variables
source $SAVE_ENVIRONNEMENT_SCRIPT
