#!/bin/sh
# swu_satte_machine - A shell script to check system state after update

# Variable
SCRIPTS_PATH="/opt/scripts"
SCRIPT_ENVIRONNEMENT="$SCRIPTS_PATH/env_var"

# Source environnement variables
source $SCRIPT_ENVIRONNEMENT

check_update_state_value () {

  case $UPDATE_STATE in 
    "WAIT") source $SCRIPT_WAIT_UPDATE ;; # All is ok
    "GET_APP_ARCHIVE_NAME" | "GET_APP_ARCHIVE" | "GET_ROOTFS_NAME" | "UPDATE_SYSTEM" |"UPDATE_APP") source $SCRIPT_GET_ARCHIVE ;; # The update was interrupted 
    "SYSTEM_UPDATED") mount $TEMP_APP_PART /APP; source $SCRIPT_ROOTFS_VERIFICATION ;; # Rootfs and Application partitions were updated
    "APP_UPDATED") mount $TEMP_APP_PART /APP ; source $SCRIPT_APP_VERIFICATION ;; # Only Application partition was updated
    esac 
}

check_update_state_value
# Save environnement variables
source $SCRIPT_SAVE_ENVIRONNEMENT
