#!/bin/sh
# save_env - A shell script to save environnement variables file


save_environnement_file () {

  for var in $(cat $SCRIPT_ENVIRONNEMENT | cut -d= -f1) 
  do 
    eval echo $var=\$$var >> "$SCRIPT_ENVIRONNEMENT.tmp"
  done

  sort -u "$SCRIPT_ENVIRONNEMENT.tmp" > $SCRIPT_ENVIRONNEMENT
  rm "$SCRIPT_ENVIRONNEMENT.tmp"
}

save_environnement_file
